### ISSUE TITLE
How can i have Realm Instead Of Room?

### ISSUE THREAD

**Issue by shriharsha-bhagwat** [arthur3486/android-mvvm#2]
How can i have Realm DB Instead Of Room?

**Comment by arthur3486** [comment]
Hi @android-bash !

Sorry for the late reply!

In order for you to be able to use the Realm DB within the application, you need to create a concrete implementation for each existing [`DataStore`](https://github.com/arthur3486/android-mvvm/tree/master/data/src/main/java/com/arthurivanets/sample/data/datastores) that would satisfy the corresponding contract (e.g. your `ComicsRealmDBDataStore` should implement the [`ComicsDataStore`](https://github.com/arthur3486/android-mvvm/blob/master/data/src/main/java/com/arthurivanets/sample/data/datastores/characters/CharactersDataStore.kt) contract); also, in each corresponding [`DataStoreFactory`](https://github.com/arthur3486/android-mvvm/blob/master/data/src/main/java/com/arthurivanets/sample/data/datastores/DataStoreFactory.kt), whenever the creation of the `DataStore` of type `DataStore.Type.DATABASE` is requested, the instantiation of the `*DatabaseDataStore` should be replaced with the instantiation of your `*RealmDatabaseDataStore` equivalent.

Hope this helps! :)

Cheers
