### ISSUE TITLE
(BUG android-mvvm version 1.2.0 )  Desktop options do not appear

### ISSUE THREAD

**Issue by friendsmobile** [arthur3486/android-mvvm#3]
# Project Information

* Repository: https://github.com/arthur3486/android-mvvm
* Project Name:   android-mvvm
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://github.com/arthur3486/android-mvvm/releases

# Expected behavior

when I try to open the application All options should appear for user 

# Actual behavior

When I open the application, no options appear and the application is buffering.

#### How to reproduce

* Download the application
*   open the application 
*   Note the Error

* Browser/App version:  1.2.0
* Operating system: 6.0

#### Recording Of The Bug

![20190727_154316](https://user-images.githubusercontent.com/51118734/61993451-ee99a700-b020-11e9-9a34-64b478d38e6f.gif)

**Comment by arthur3486** [comment]
Hi @friendsmobile !

I believe it had something to do with the Marvel API (e.g. exceeded quota), because I just checked the application and can confirm that everything works as expected.
